### ISSUE TITLE
Running over Thread.java doesn't emit method names

### ISSUE THREAD

**Issue by borkdude** [allnulled/javadoc#1]
When I run over `Thread.java` from e.g. https://github.com/openjdk/jdk.git for the method names I see `"default"`.

E.g. for the method `sleep`:

```
[
            {
                "name": "default",
                "text": "\n\nCauses the currently executing thread to sleep (temporarily cease\nexecution) for the specified number of milliseconds, subject to\nthe precision and accuracy of system timers and schedulers. The thread\ndoes not lose ownership of any monitors.\n"
            },
            {
                "name": "@param",
                "text": " millis\n       the length of time to sleep in milliseconds\n"
            },
            {
                "name": "@throws",
                "text": " IllegalArgumentException\n        if the value of {@code millis} is negative\n"
            },
            {
                "name": "@throws",
                "text": " InterruptedException\n        if any thread has interrupted the current thread. The\n        <i>interrupted status</i> of the current thread is\n        cleared when this exception is thrown."
            }
        ]
```

Is this something that can be fixed?

**Comment by allnulled** [comment]
Hello, sir.

For a comment like this one:

```java
    /**
     * Causes the currently executing thread to sleep (temporarily cease
     * execution) for the specified number of milliseconds, subject to
     * the precision and accuracy of system timers and schedulers. The thread
     * does not lose ownership of any monitors.
     *
     * @param  millis
     *         the length of time to sleep in milliseconds
     *
     * @throws  IllegalArgumentException
     *          if the value of {@code millis} is negative
     *
     * @throws  InterruptedException
     *          if any thread has interrupted the current thread. The
     *          <i>interrupted status</i> of the current thread is
     *          cleared when this exception is thrown.
     */
```

That is the output expected to show by this simple tool.

I suppose that you expected to find already the name of the method in this JSON, or other information which is inherent of the language that is underlying these javadoc comments. But... I am afraid that this tool is not thought to accomplish code analysis tasks. It was more thought to create Markdown and JSON output from source code comments of any language that accepts the typical `/* multiline comments */` of this type, but without caring about the contextual programming language, or the data that could be extracted from it.

Thinking about minimalism.

For that piece of code to work well with this, it should also specify something like `@name javal.lang.Thread.sleep` in the javadoc comment. In that case, the tool would do the trick.

If you take a look to this piece of code, you can see that it is not much more of 1 hundred lines, or so, and it does not care about the programming language that is running under it, so it could lead to problems when mixing multiline strings and javadoc expressions in them. I should specify that in the README.

So... no, sorry, sir, but that issue would be out of the scope of the proposals of this tool, which is very focused on minimalism. What you say would require some more complex operations.

And sorry for the delay of my answer, I have just seen the issue this late.

Thank you.
