### ISSUE TITLE
Installing OSX to override Javadoc

### ISSUE THREAD

**Issue by shanerk** [allnulled/javadoc#2]
I have Java 1.8 installed on OSX and the built-in javadoc is not letting me run this from the command line.  Is there a way to override it or perhaps specify a different name when installing with -g ?

**Comment by shanerk** [comment]
Hey man, I initially forked this but ended up creating my own repo based partially on your code.  I've taken it so far away from what you are doing here that it made no sense for it to continue to be something you'd ever want to merge back in.  My use case is to support JS, Salesforce Apex and Java (and ultimately C# as well) to generate API docs in markdown.  Take a look here: https://github.com/shanekenyon87/javadoc2

**Comment by allnulled** [comment]
Sorry, man, I do not know why, but I never noticed this issue.

I am updating a new version of the package.

This project, though, is not related to Java at all. It only takes the general idea from the traditional JavaDoc project, but it is language-unopinionated.

It can work for PHP, Node, Java, or anything else. This implies that this project DOES NOT parse source code, it only generates documentation based on regular expressions.

Sorry for the midunderstanding.

**Comment by allnulled** [comment]
I'm closing the issue, I see your profile has been out for long time.
